### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ScorpThePotato** [ScorpThePotato/nvchad#1]
- [ ] Look into codeium.vim
- [ ] Add nvim-neoclip.lua
- [ ] Complete remapping
- [x] #2 
- [x] Clean up plugins file
- [x] Look into nvim-toggler
- [x] Configure lazygit `Replaced with fugitive`
- [x] Remove ChatGPT
- [x] Configure NvDash to launch on startup
